runtime: python38
entrypoint: gunicorn -b :$PORT main:app
env_variables:
  CLOUDSQL_USER: root
  CLOUDSQL_DB: carbon_calories
  CLOUDSQL_PASSWORD: CarbonCalories123@
  CLOUDSQL_DSN: carbon-calories:us-east1:carbon-calories-database
handlers:
- url: /static
  static_dir: static